- hosts: all
  vars_files:
    - secrets.yml
  remote_user: "{{ user }}"
  become_user: "{{ user }}"
  tasks:
    - name: Log into private registry and force re-authorization
      become: True
      shell: "/usr/bin/docker login {{ registry_host }} -u {{ registry_user }} -p {{ registry_password }}"
      args:
        chdir: "/home/{{ user }}/compose"
        executable: /usr/bin/zsh
    - name: Restart Container
      become: True
      shell: "/usr/bin/docker stack deploy -c turnstile.yml turnstile"
      args:
        chdir: "/home/{{ user }}/compose"
        executable: "/usr/bin/zsh"
