- hosts: all
  vars_files:
    - secrets.yml
  remote_user: "{{ user }}"
  become_user: "{{ user }}"
  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{ registry_host }}"
        username: "{{ registry_user }}"
        password: "{{ registry_password }}"
        reauthorize: yes
    - name: Restart Container
      become: True
      shell: /usr/bin/docker service update --force turnstile_turnstile
      args:
        chdir: /hoe/{{ user }}/compose
        executable: /bin/zsh
