name: ci-dev

on:
  push:
    branches:
      - 'main'
jobs:
  docker-build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: create application.yaml and koin.properties
        run: |
          touch ./src/main/resources/application.yaml
          echo "${{ secrets.APPLICATION_YAML }}" >> ./src/main/resources/application.yaml
          touch ./src/main/resources/koin.properties
          echo "${{ secrets.KOIN_PROPERTIES }}" >> ./src/main/resources/koin.properties
      - name: Build and push
        run: |
          export REGISTRY_HOST=${{ secrets.REGISTRY_HOST }}
          export REGISTRY_ID=${{ secrets.REGISTRY_ID }}
          export REGISTRY_PASSWORD=${{ secrets.REGISTRY_PASSWORD }}
          ./gradlew publishImage
  docker-swarm-deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_ID }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.ANSIBLE_USER }}
          remote_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          stack_file: "/home/limdongyoung0/compose/turnstile.yml"
          stack_name: "turnstile"
